#!/usr/bin/env python3
"""Render field checklists from task checklist memberships."""

from __future__ import annotations

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TASKS = ROOT / "data" / "tasks"
DEFAULT_OUTPUT = ROOT / "build" / "checklists"
REFERENCE = re.compile(
    r"(?P<icon>📋|🌐|🍷|🔥|🏕️|🍳|🔧|📦)\s+"
    r"(?P<name>[A-Za-z0-9][A-Za-z0-9_-]*)"
)


def text(element: ET.Element | None) -> str:
    if element is None:
        return ""
    return " ".join("".join(element.itertext()).split())


def output_name(checklist_type: str) -> str:
    return re.sub(r"[^A-Za-z0-9_-]+", "_", checklist_type).strip("_") + ".md"


def humanize(value: str) -> str:
    return REFERENCE.sub(
        lambda match: f"{match.group('icon')} {match.group('name').replace('_', ' ')}",
        value,
    )


def task_memberships() -> dict[str, list[tuple[str, str]]]:
    memberships: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for task_path in sorted(TASKS.glob("*.xml")):
        task = ET.parse(task_path).getroot()
        task_name = text(task.find("name"))
        when = text(task.find("when"))
        for element in task.findall("./checklist_types/checklist_type"):
            checklist_type = text(element)
            if checklist_type:
                memberships[checklist_type].append((task_name, when))
    return dict(memberships)


def render(checklist_type: str, tasks: list[tuple[str, str]]) -> str:
    lines = [
        "<!-- Generated from canonical XML. Do not edit this file directly. -->",
        "",
        f"# {checklist_type} checklist",
        "",
        "This is an assignment and status index, not an execution sequence. "
        "Follow each task's **When** condition and linked task card. Mark one "
        "status for every row: `PASS`, `BLOCKED`, `ESCALATED`, or "
        "`NOT APPLICABLE`.",
        "",
        "| Task | When | Status | Initials | Completion time |",
        "| --- | --- | --- | --- | --- |",
    ]
    for task_name, when in sorted(tasks, key=lambda value: value[0].casefold()):
        label = task_name.replace("_", " ")
        lines.append(
            f"| [📋 {label}](../task-cards/{task_name}.md) | {humanize(when)} |  |  |  |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Directory for generated Markdown checklists.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when generated output is stale.",
    )
    args = parser.parse_args()

    try:
        memberships = task_memberships()
    except (OSError, ET.ParseError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    output_dir = args.output_dir.resolve()
    jobs = {
        output_dir / output_name(checklist_type): render(checklist_type, tasks)
        for checklist_type, tasks in sorted(memberships.items())
    }

    if args.check:
        stale: list[Path] = []
        for output, rendered in jobs.items():
            try:
                if output.read_text(encoding="utf-8") != rendered:
                    stale.append(output)
            except OSError:
                stale.append(output)
        extras = sorted(output_dir.glob("*.md")) if output_dir.is_dir() else []
        extras = [path for path in extras if path not in jobs]
        if stale or extras:
            for output in stale:
                print(f"error: rendered checklist is stale: {output}", file=sys.stderr)
            for output in extras:
                print(f"error: orphaned checklist: {output}", file=sys.stderr)
            return 1
        print(f"All {len(jobs)} checklists are current.")
        return 0

    output_dir.mkdir(parents=True, exist_ok=True)
    for output, rendered in jobs.items():
        output.write_text(rendered, encoding="utf-8")
        print(f"Rendered {output.relative_to(ROOT.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
