#!/usr/bin/env python3
"""Render one self-contained Markdown task card from canonical XML."""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

from render_helpers import humanize_references, item_for_reference, text

ROOT = Path(__file__).resolve().parents[1]


def humanize(value: str) -> str:
    return humanize_references(value, keep_icons=True)


def render(task_path: Path) -> str:
    task = ET.parse(task_path).getroot()
    task_name = text(task.find("name"))
    resources: list[ET.Element | None] = []
    resource_values: list[str] = []
    for resource in task.findall("./resources/resource"):
        value = text(resource)
        resource_values.append(value)
        resources.append(item_for_reference(value))

    lines = [
        "<!-- Generated from canonical XML. Do not edit this file directly. -->",
        "",
        f"# 📋 {task_name.replace('_', ' ')}",
        "",
    ]

    checklist_types = [
        text(element)
        for element in task.findall("./checklist_types/checklist_type")
        if text(element)
    ]
    lines.append(f"- **Checklist types:** {', '.join(checklist_types)}")
    lines.append(f"- **Area:** {text(task.find('area'))}")
    why = text(task.find("why"))
    if why:
        lines.append(f"- **Why:** {humanize(why)}")
    lines.append(f"- **When:** {humanize(text(task.find('when')))}")
    duration = text(task.find("time"))
    if duration:
        lines.append(f"- **Time:** {duration}")

    lines.extend(["", "## What you need", ""])
    for value, item in zip(resource_values, resources):
        label = humanize(value)
        if item is None:
            lines.append(f"- {label}")
            continue
        details = [
            humanize(text(item.find("location")).rstrip(".")),
            humanize(text(item.find("description")).rstrip(".")),
        ]
        details = [detail for detail in details if detail]
        suffix = f" — {'. '.join(details)}." if details else ""
        lines.append(f"- {label}{suffix}")

    ready_before = [
        (value, text(item.find("readyBeforeUse")))
        for value, item in zip(resource_values, resources)
        if item is not None and text(item.find("readyBeforeUse"))
    ]
    if ready_before:
        lines.extend(["", "## Ready before normal use", ""])
        for value, condition in ready_before:
            lines.append(f"- **{humanize(value)}:** {humanize(condition)}")

    lines.extend(["", "## Steps", ""])
    for step in task.findall("./steps/step"):
        number = step.get("number", "")
        lines.append(f"{number}. {humanize(text(step.find('action')))}")
        expected = text(step.find("expectedResult"))
        if expected:
            lines.append(f"   - **EXPECTED:** {humanize(expected)}")
        branch = text(step.find("ifThen"))
        if branch:
            lines.append(f"   - **IF/THEN:** {humanize(branch)}")

    lines.extend(["", "## PASS when", ""])
    for criterion in task.findall("./passWhen/criterion"):
        lines.append(f"- {humanize(text(criterion))}")

    lines.extend(["", "## Finish", ""])
    global_root = ET.parse(ROOT / "data" / "global-instructions.xml").getroot()
    for instruction in global_root.findall("./instruction"):
        lines.append(f"- {humanize(text(instruction))}")

    lines.extend(["", "### Leave items ready", ""])
    for value, item in zip(resource_values, resources):
        if item is None:
            continue
        ready = text(item.find("readyForNextPerson"))
        if ready:
            lines.append(f"- **{humanize(value)}:** {humanize(ready)}")

    not_ready = [
        (value, text(item.find("ifNotReady")))
        for value, item in zip(resource_values, resources)
        if item is not None
        and text(item.find("ifNotReady"))
        and f"📋 {task_name}" not in text(item.find("ifNotReady"))
    ]
    if not_ready:
        lines.extend(["", "### If an item is not ready", ""])
        for value, response in not_ready:
            lines.append(f"- **{humanize(value)}:** {humanize(response)}")

    problems: list[tuple[str | None, str, str]] = []
    for problem in task.findall("./commonProblems/problem"):
        problems.append(
            (None, text(problem.find("condition")), text(problem.find("response")))
        )
    for value, item in zip(resource_values, resources):
        if item is None:
            continue
        for problem in item.findall("./commonProblems/problem"):
            problems.append(
                (
                    humanize(value),
                    text(problem.find("condition")),
                    text(problem.find("response")),
                )
            )
    if problems:
        lines.extend(["", "## Common problems", ""])
        for item_label, condition, response in problems:
            prefix = f"**{item_label}:** " if item_label else ""
            lines.append(
                f"- {prefix}**IF** {humanize(condition).rstrip('.')} **THEN** "
                f"{humanize(response)}"
            )

    expert = text(task.find("expert")) or "Dominatrix"
    lines.extend(["", "## Who to ask", "", expert, ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("task_xml", nargs="?", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument(
        "--all",
        action="store_true",
        help="Render every canonical task to build/task-cards.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=ROOT / "build" / "task-cards",
        help="Output directory used with --all.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when the existing output is stale.",
    )
    args = parser.parse_args()

    if args.all:
        if args.task_xml is not None or args.output is not None:
            parser.error("--all cannot be combined with task_xml or --output")
        jobs = [
            (task_path, args.output_dir / f"{task_path.stem}.md")
            for task_path in sorted((ROOT / "data" / "tasks").glob("*.xml"))
        ]
    else:
        if args.task_xml is None or args.output is None:
            parser.error("task_xml and --output are required unless --all is used")
        jobs = [(args.task_xml, args.output)]

    stale: list[Path] = []
    for task_path, output_path in jobs:
        try:
            rendered = render(task_path.resolve())
        except (OSError, ET.ParseError, KeyError) as exc:
            print(f"error: {task_path}: {exc}", file=sys.stderr)
            return 1

        output = output_path.resolve()
        if args.check:
            try:
                existing = output.read_text(encoding="utf-8")
            except OSError:
                stale.append(output)
                continue
            if existing != rendered:
                stale.append(output)
            continue

        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8")
        print(f"Rendered {output.relative_to(ROOT.parent)}")

    if stale:
        for output in stale:
            print(f"error: rendered task card is stale: {output}", file=sys.stderr)
        return 1
    if args.check:
        if args.all:
            expected = {output_path.resolve() for _, output_path in jobs}
            extras = sorted(args.output_dir.resolve().glob("*.md"))
            extras = [path for path in extras if path not in expected]
            if extras:
                for output in extras:
                    print(f"error: orphaned task card: {output}", file=sys.stderr)
                return 1
        print(f"All {len(jobs)} task cards are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
