#!/usr/bin/env python3
"""Render one self-contained Markdown task card from canonical XML."""

from __future__ import annotations

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ITEMS = ROOT / "data" / "items"
ITEM_FOLDERS = {
    "🌐": ITEMS / "public area",
    "🍷": ITEMS / "bar-cheese",
    "🔥": ITEMS / "propane area",
    "🏕️": ITEMS / "common area",
    "🍳": ITEMS / "kitchen",
    "🔧": ITEMS / "private infrastructure",
    "📦": ITEMS,
}
REFERENCE = re.compile(
    r"(?P<icon>📋|🌐|🍷|🔥|🏕️|🍳|🔧|📦)\s+"
    r"(?P<name>[A-Za-z0-9][A-Za-z0-9_-]*)"
)


def text(element: ET.Element | None) -> str:
    if element is None:
        return ""
    return " ".join("".join(element.itertext()).split())


def humanize(value: str) -> str:
    return REFERENCE.sub(
        lambda match: f"{match.group('icon')} {match.group('name').replace('_', ' ')}",
        value,
    )


def item_for_reference(value: str) -> ET.Element | None:
    match = REFERENCE.fullmatch(value)
    if not match or match.group("icon") == "📋":
        return None
    path = ITEM_FOLDERS[match.group("icon")] / f"{match.group('name')}.xml"
    return ET.parse(path).getroot()


def render(task_path: Path) -> str:
    task = ET.parse(task_path).getroot()
    task_name = text(task.find("name"))
    resources: list[ET.Element | None] = []
    resource_values: list[str] = []
    for resource in task.findall("./resources/resource"):
        value = text(resource)
        resource_values.append(value)
        resources.append(item_for_reference(value))

    lines = [
        "<!-- Generated from canonical XML. Do not edit this file directly. -->",
        "",
        f"# 📋 {task_name.replace('_', ' ')}",
        "",
    ]

    checklist_types = [
        text(element)
        for element in task.findall("./checklist_types/checklist_type")
        if text(element)
    ]
    lines.append(f"- **Checklist types:** {', '.join(checklist_types)}")
    lines.append(f"- **Area:** {text(task.find('area'))}")
    why = text(task.find("why"))
    if why:
        lines.append(f"- **Why:** {humanize(why)}")
    lines.append(f"- **When:** {humanize(text(task.find('when')))}")
    duration = text(task.find("time"))
    if duration:
        lines.append(f"- **Time:** {duration}")

    lines.extend(["", "## What you need", ""])
    for value, item in zip(resource_values, resources):
        label = humanize(value)
        if item is None:
            lines.append(f"- {label}")
            continue
        details = [
            text(item.find("location")).rstrip("."),
            text(item.find("description")).rstrip("."),
        ]
        details = [detail for detail in details if detail]
        suffix = f" — {'. '.join(details)}." if details else ""
        lines.append(f"- {label}{suffix}")

    ready_before = [
        (value, text(item.find("readyBeforeUse")))
        for value, item in zip(resource_values, resources)
        if item is not None and text(item.find("readyBeforeUse"))
    ]
    if ready_before:
        lines.extend(["", "## Before starting", ""])
        for value, condition in ready_before:
            lines.append(f"- **{humanize(value)}:** {humanize(condition)}")

    lines.extend(["", "## Steps", ""])
    for step in task.findall("./steps/step"):
        number = step.get("number", "")
        lines.append(f"{number}. {humanize(text(step.find('action')))}")
        expected = text(step.find("expectedResult"))
        if expected:
            lines.append(f"   - **EXPECTED:** {humanize(expected)}")
        branch = text(step.find("ifThen"))
        if branch:
            lines.append(f"   - **IF/THEN:** {humanize(branch)}")

    lines.extend(["", "## PASS when", ""])
    for criterion in task.findall("./passWhen/criterion"):
        lines.append(f"- {humanize(text(criterion))}")

    lines.extend(["", "## Finish", ""])
    global_root = ET.parse(ROOT / "data" / "global-instructions.xml").getroot()
    for instruction in global_root.findall("./instruction"):
        lines.append(f"- {humanize(text(instruction))}")

    lines.extend(["", "### Leave items ready", ""])
    for value, item in zip(resource_values, resources):
        if item is None:
            continue
        ready = text(item.find("readyForNextPerson"))
        if ready:
            lines.append(f"- **{humanize(value)}:** {humanize(ready)}")

    not_ready = [
        (value, text(item.find("ifNotReady")))
        for value, item in zip(resource_values, resources)
        if item is not None
        and text(item.find("ifNotReady"))
        and f"📋 {task_name}" not in text(item.find("ifNotReady"))
    ]
    if not_ready:
        lines.extend(["", "### If an item is not ready", ""])
        for value, response in not_ready:
            lines.append(f"- **{humanize(value)}:** {humanize(response)}")

    problems: list[tuple[str | None, str, str]] = []
    for problem in task.findall("./commonProblems/problem"):
        problems.append(
            (None, text(problem.find("condition")), text(problem.find("response")))
        )
    for value, item in zip(resource_values, resources):
        if item is None:
            continue
        for problem in item.findall("./commonProblems/problem"):
            problems.append(
                (
                    humanize(value),
                    text(problem.find("condition")),
                    text(problem.find("response")),
                )
            )
    if problems:
        lines.extend(["", "## Common problems", ""])
        for item_label, condition, response in problems:
            prefix = f"**{item_label}:** " if item_label else ""
            lines.append(
                f"- {prefix}**IF** {humanize(condition).rstrip('.')} **THEN** "
                f"{humanize(response)}"
            )

    expert = text(task.find("expert")) or "Dominatrix"
    lines.extend(["", "## Who to ask", "", expert, ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("task_xml", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when the existing output is stale.",
    )
    args = parser.parse_args()

    try:
        rendered = render(args.task_xml.resolve())
    except (OSError, ET.ParseError, KeyError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    output = args.output.resolve()
    if args.check:
        try:
            existing = output.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"error: cannot check {output}: {exc}", file=sys.stderr)
            return 1
        if existing != rendered:
            print(f"error: rendered task card is stale: {output}", file=sys.stderr)
            return 1
        print(f"Task card is current: {output.relative_to(ROOT.parent)}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    print(f"Rendered {output.relative_to(ROOT.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
